
 
CREATE TABLE CUSTOMER (
	CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CUSTOMER_PK PRIMARY KEY,
	NAME VARCHAR2 ( 60 ) NOT NULL,
	EMAIL VARCHAR2 ( 40 ) NOT NULL UNIQUE,
	PASSWORD VARCHAR2 ( 30 ) NOT NULL,
	PHONE_NUMBER VARCHAR2 ( 20 ) NOT NULL,
	ADDRESS VARCHAR2 ( 250 ),
	REG_DATE DATE DEFAULT SYSDATE,
	TOTAL_SERVICES_TAKEN NUMBER 
);
CREATE TABLE SERVICE_PROVIDER (
	PROVIDER_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PROVIDER_PK PRIMARY KEY,
	NAME VARCHAR2 ( 40 ) NOT NULL,
	EMAIL VARCHAR2 ( 40 ) NOT NULL UNIQUE,
	PASSWORD VARCHAR2 ( 30 ) NOT NULL,
	PHONE_NUMBER VARCHAR2 ( 20 ) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE,
	INCOME NUMBER,
	LICENCE_ID VARCHAR2 ( 40 )
);


CREATE TABLE RATINGS ( REVIEW_ID NUMBER CONSTRAINT RATINGS_PK PRIMARY KEY, STAR NUMBER, COMMENTS VARCHAR2 ( 600 ), C_ID NUMBER, CAT_ID NUMBER );
ALTER TABLE RATINGS ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY ( C_ID ) REFERENCES CUSTOMER ( CUSTOMER_ID ) ON DELETE 
SET NULL;



CREATE TABLE CATEGORY ( CATEGORY_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CATEGORY_PK PRIMARY KEY, CATEGORY_NAME VARCHAR2 ( 50 ) NOT NULL, DESCRIPTION VARCHAR2 ( 500 ) );

ALTER TABLE RATINGS ADD CONSTRAINT FK_PROVIDER FOREIGN KEY ( CAT_ID ) REFERENCES CATEGORY ( CATEGORY_ID ) ON DELETE 
SET NULL;

CREATE TABLE SERVICE (
	SERVICE_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT SERVICE_PK PRIMARY KEY,
	SERVICE_NAME VARCHAR2 ( 100 ) NOT NULL,
	DESCRIPTION VARCHAR2 ( 500 ),
	COST NUMBER NOT NULL,
	CATEGORY_ID NUMBER 
);


ALTER TABLE SERVICE ADD CONSTRAINT FK_CATEGORY FOREIGN KEY ( CATEGORY_ID ) REFERENCES CATEGORY ( CATEGORY_ID ) ON DELETE 
SET NULL;
ALTER TABLE SERVICE_PROVIDER ADD PROVIDES NUMBER;
ALTER TABLE SERVICE_PROVIDER ADD CONSTRAINT FK_PROVIDES FOREIGN KEY ( PROVIDES ) REFERENCES SERVICE ( SERVICE_ID ) ON DELETE 
SET NULL;


CREATE TABLE ORDERS (
	ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	ORDER_ADDRESS VARCHAR2 ( 100 ) NOT NULL,
	ORDER_NOTES VARCHAR2 ( 500 ),
	ORDER_STATUS VARCHAR2 ( 20 ),
	C_ID NUMBER,
	PRIMARY KEY(ORDER_ID)
);


CREATE TABLE PAYMENT_INFO ( PAYMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PAYMENT_INFO_PK PRIMARY KEY, ORDER_ID NUMBER, AMOUNT NUMBER NOT NULL, METHOD VARCHAR2 ( 20 ) NOT NULL, TRANSACTION_ID VARCHAR2 ( 30 ) );
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDEREDBY FOREIGN KEY ( C_ID ) REFERENCES CUSTOMER ( CUSTOMER_ID ) ON DELETE 
SET NULL;
ALTER TABLE PAYMENT_INFO ADD CONSTRAINT FK_ORDER FOREIGN KEY ( ORDER_ID ) REFERENCES ORDERS ( ORDER_ID ) ON DELETE 
SET NULL;

CREATE TABLE OFFERS (
OFFER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
SERVICE_ID NUMBER,
OFFER_NAME VARCHAR2(40) ,
DISCOUNT NUMBER,
START_DATE DATE DEFAULT SYSDATE,
END_DATE DATE NOT NULL,
CONSTRAINT OFFERS_PK PRIMARY KEY(OFFER_ID,SERVICE_ID)
);

ALTER TABLE OFFERS 
ADD CONSTRAINT FK_SERVICE_OFFER
FOREIGN KEY(SERVICE_ID)
REFERENCES SERVICE(SERVICE_ID)
ON DELETE CASCADE;

CREATE TABLE MODERATOR (
MODERATOR_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT MODERATOR_PK PRIMARY KEY,
MODERATOR_NAME VARCHAR2(40) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL UNIQUE,
PASSWORD VARCHAR2(30) NOT NULL,
PHONE_NO VARCHAR2(20) NOT NULL,
PRESENT_ADDRESS VARCHAR2(100),
PERMANENT_ADDRESS VARCHAR2(100),
SALARY NUMBER ,
BANK_ACCOUNT_NO VARCHAR2(30),
HIRE_DATE DATE DEFAULT SYSDATE,
END_DATE DATE 
);

ALTER TABLE CATEGORY 
ADD MODERATED_BY NUMBER;

ALTER TABLE CATEGORY 
ADD CONSTRAINT FK_MODERATES
FOREIGN KEY(MODERATED_BY)
REFERENCES MODERATOR(MODERATOR_ID)
ON DELETE SET NULL;


CREATE TABLE ACCOUNT(
TRANSACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT ACCOUNT_PK PRIMARY KEY,
DEBIT NUMBER,
CREDIT NUMBER,
CURRENT_AMOUNT NUMBER,
PAYMENT_ID NUMBER
);

ALTER TABLE ACCOUNT 
ADD CONSTRAINT FK_PAYMENT
FOREIGN KEY(PAYMENT_ID)
REFERENCES PAYMENT_INFO(PAYMENT_ID)
ON DELETE CASCADE;

CREATE TABLE INCLUDED_IN (
SVC_ID NUMBER,
ORDER_ID NUMBER,
ORDER_STATUS VARCHAR2(15),
CONSTRAINT INCLUDED_IN_PK PRIMARY KEY (SVC_ID, ORDER_ID)
);

ALTER TABLE INCLUDED_IN 
ADD CONSTRAINT FK_INCLUDED_IN
FOREIGN KEY(SVC_ID)
REFERENCES SERVICE(SERVICE_ID)
ON DELETE CASCADE;

ALTER TABLE INCLUDED_IN 
ADD CONSTRAINT FK_INCLUDED_IN_2
FOREIGN KEY(ORDER_ID)
REFERENCES ORDERS(ORDER_ID)
ON DELETE CASCADE;


ALTER TABLE CUSTOMER ADD TOKEN VARCHAR2(200);