CREATE OR REPLACE TRIGGER ACCOUNT_TRANSACTION 
AFTER INSERT
ON PAYMENT_INFO
FOR EACH ROW

DECLARE 


BEGIN 

INSERT INTO ACCOUNT(DEBIT, CREDIT, CURRENT_AMOUNT, PAYMENT_ID) VALUES(0, :NEW.AMOUNT, :NEW.AMOUNT, :NEW.PAYMENT_ID);

END;


CREATE OR REPLACE TRIGGER UPDATE_ACCOUNT_TRANSACTION
AFTER UPDATE
ON INCLUDED_IN
FOR EACH ROW
WHEN(NEW.ORDER_STATUS = 'COMPLETED')
 
DECLARE
PID NUMBER;
OID NUMBER;
NEWDEB NUMBER;

BEGIN 

OID := :OLD.ORDER_ID;
NEWDEB := :OLD.COST*0.75;


SELECT PAYMENT_ID INTO PID FROM PAYMENT_INFO WHERE ORDER_ID = OID;

UPDATE ACCOUNT SET DEBIT = (DEBIT + NEWDEB) , CURRENT_AMOUNT = (CURRENT_AMOUNT - NEWDEB) , TRANS_DATE = SYSDATE
WHERE PAYMENT_ID = PID;

UPDATE SERVICE_PROVIDER SET INCOME = NVL(INCOME,0) + NEWDEB WHERE PROVIDER_ID = :OLD.PROVIDER_ID;

END;