CREATE OR REPLACE TRIGGER UPDATE_ORDER_STATUS 
AFTER UPDATE 
ON INCLUDED_IN
FOR EACH ROW
WHEN(NEW.ORDER_STATUS = 'COMPLETED')

DECLARE 
CNT_ALL NUMBER;
CNT NUMBER;

BEGIN 

SELECT COUNT(*) INTO CNT FROM INCLUDED_IN WHERE ORDER_ID = :OLD.ORDER_ID AND ORDER_STATUS='COMPLETED';
SELECT COUNT(*) INTO CNT_ALL FROM INCLUDED_IN WHERE ORDER_ID = :OLD.ORDER_ID;

IF CNT = CNT_ALL THEN
UPDATE ORDERS SET ORDER_STATUS = 'COMPLETED' WHERE ORDER_ID = :OLD.ORDER_ID;
END IF;

END;
