CREATE 
	OR REPLACE PROCEDURE CREATE_CART ( CID IN CART.C_ID%TYPE, SID IN CART.S_ID%TYPE, QUAN IN CART.QUANTITY%TYPE ) IS TEMP_PRICE NUMBER;
CNT NUMBER;
BEGIN
		TEMP_PRICE := 0;
	SELECT
		COUNT( * ) INTO CNT 
	FROM
		OFFERS 
	WHERE
		OFFERS.SERVICE_ID = SID;
	IF
		CNT > 0 THEN
		SELECT
			( S.COST - S.COST * ( O.DISCOUNT / 100 ) ) INTO TEMP_PRICE 
		FROM
			SERVICE S
			JOIN OFFERS O ON ( S.SERVICE_ID = O.SERVICE_ID ) 
		WHERE
			O.SERVICE_ID = SID;
		ELSE SELECT
			COST INTO TEMP_PRICE 
		FROM
			SERVICE 
		WHERE
			SERVICE_ID = SID;
		
	END IF;

INSERT INTO CART (S_ID, C_ID, QUANTITY, PRICE) VALUES(SID, CID, QUAN, TEMP_PRICE);
END;