CREATE OR REPLACE PROCEDURE INSERT_ORDERS(CID IN ORDERS.C_ID%TYPE, ADDRESS IN ORDERS.ORDER_ADDRESS%TYPE, NOTES IN ORDERS.ORDER_NOTES%TYPE, U_AMOUNT IN PAYMENT_INFO.AMOUNT%TYPE, U_METHOD IN PAYMENT_INFO.METHOD%TYPE, U_TRANSACTION_ID IN PAYMENT_INFO.TRANSACTION_ID%TYPE, U_PAY_PHONE IN PAYMENT_INFO.PAY_PHONE%TYPE) IS 

OID NUMBER;

BEGIN 

OID := ORDER_SEQ.NEXTVAL;

INSERT INTO ORDERS(ORDER_ID, ORDER_ADDRESS, ORDER_NOTES, ORDER_STATUS, C_ID)
VALUES(OID, ADDRESS, NOTES, 'PENDING', CID);

INSERT INTO PAYMENT_INFO(ORDER_ID, AMOUNT, METHOD, TRANSACTION_ID, PAY_PHONE) VALUES(OID, U_AMOUNT, U_METHOD, U_TRANSACTION_ID, U_PAY_PHONE);

END;