CREATE OR REPLACE PROCEDURE INSERT_ORDERS(CID IN ORDERS.C_ID%TYPE, ADDRESS IN ORDERS.ORDER_ADDRESS%TYPE, NOTES IN ORDERS.ORDER_NOTES%TYPE, U_AMOUNT IN PAYMENT_INFO.AMOUNT%TYPE, U_METHOD IN PAYMENT_INFO.METHOD%TYPE, U_TRANSACTION_ID IN PAYMENT_INFO.TRANSACTION_ID%TYPE, U_PAY_PHONE IN PAYMENT_INFO.PAY_PHONE%TYPE) IS 

OID NUMBER;

BEGIN 

OID := ORDER_SEQ.NEXTVAL;

INSERT INTO ORDERS(ORDER_ID, ORDER_ADDRESS, ORDER_NOTES, ORDER_STATUS, C_ID)
VALUES(OID, ADDRESS, NOTES, 'PENDING', CID);

INSERT INTO PAYMENT_INFO(ORDER_ID, AMOUNT, METHOD, TRANSACTION_ID, PAY_PHONE) VALUES(OID, U_AMOUNT, U_METHOD, U_TRANSACTION_ID, U_PAY_PHONE);

END;



CREATE OR REPLACE PROCEDURE UPDATE_ORDER_STATUS(OID IN INCLUDED_IN.ORDER_ID%TYPE) IS 

CNT NUMBER;
CNT_ALL NUMBER;

BEGIN 

SELECT COUNT(*) INTO CNT FROM INCLUDED_IN WHERE ORDER_ID = OID AND ORDER_STATUS='COMPLETED';
SELECT COUNT(*) INTO CNT_ALL FROM INCLUDED_IN WHERE ORDER_ID = OID;

IF CNT = CNT_ALL THEN 
UPDATE ORDERS SET ORDERS.ORDER_STATUS = 'COMPLETED' WHERE ORDER_ID = OID;
END IF;

END;