CREATE 
	OR REPLACE PROCEDURE ASSIGN_ORDER ( PID IN INCLUDED_IN.PROVIDER_ID%TYPE, SID IN INCLUDED_IN.SVC_ID%TYPE, OID IN INCLUDED_IN.ORDER_ID%TYPE, MSG OUT VARCHAR2 ) IS CNT NUMBER;
BEGIN
	SELECT
		COUNT( * ) INTO CNT 
	FROM
		INCLUDED_IN 
	WHERE
		SVC_ID = SID 
		AND ORDER_ID = OID 
		AND ORDER_STATUS = 'PENDING';
	IF
		CNT > 0 THEN
			UPDATE INCLUDED_IN 
			SET PROVIDER_ID = PID, ORDER_STATUS = 'ACCEPTED'
		WHERE
			SVC_ID = SID 
			AND ORDER_ID = OID;
		MSG := 'SUCCESSFUL';
		ELSE MSG := 'UNSUCCESSFUL';
		
	END IF;
END;